server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: USER_SERVICE


spring.datasource:
  tomcat:
    driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/microservices
  username: postgres
  password: postgres



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


